# Generated by Django 5.0.3 on 2024-05-02 20:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'offre'), ('1', 'demande')], max_length=1)),
                ('date', models.DateField(default=datetime.date.today, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.poste')),
                ('typeStg', models.CharField(choices=[('1', 'ouvrier'), ('2', 'technicien'), ('3', 'pfe')], max_length=1)),
                ('société', models.CharField(max_length=50)),
                ('durée', models.IntegerField()),
                ('sujet', models.CharField(max_length=50)),
                ('contactinfo', models.CharField(max_length=50)),
                ('spécialite', models.CharField(choices=[('1', 'ouvrier'), ('2', 'technicien'), ('3', 'pfe')], default='', max_length=255)),
            ],
            bases=('posts.poste',),
        ),
    ]
