# Generated by Django 5.0.3 on 2024-05-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='spécialite',
            field=models.CharField(max_length=255),
        ),
    ]
