# Generated by Django 5.0.3 on 2024-04-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('téléphone', models.CharField(max_length=8)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
