# Generated by Django 5.0.3 on 2024-05-02 20:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evénement',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.poste')),
                ('intitulé', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=50)),
                ('contactInfo', models.CharField(max_length=50)),
            ],
            bases=('posts.poste',),
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.poste')),
                ('localisation', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('contactinfo', models.CharField(max_length=100)),
            ],
            bases=('posts.poste',),
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.poste')),
                ('text', models.CharField(max_length=50)),
            ],
            bases=('posts.poste',),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.poste')),
                ('depart', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('heure_dep', models.DateTimeField(default=django.utils.timezone.now)),
                ('nbre_sièges', models.IntegerField()),
                ('contactinfo', models.CharField(max_length=100)),
            ],
            bases=('posts.poste',),
        ),
        migrations.CreateModel(
            name='EvenClub',
            fields=[
                ('evénement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.evénement')),
                ('club', models.CharField(max_length=50)),
            ],
            bases=('student.evénement',),
        ),
        migrations.CreateModel(
            name='EvenSocial',
            fields=[
                ('evénement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.evénement')),
                ('prix', models.FloatField()),
            ],
            bases=('student.evénement',),
        ),
        migrations.CreateModel(
            name='Réaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('like', models.BooleanField(default=False)),
                ('poste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.poste')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.user')),
            ],
        ),
    ]
